language: cpp

git:
    depth: 5

branches:
  only:
    - master
    - develop
 	
matrix:
  include: 
    - os: linux
      env: COMPILER=g++-4.8 LUA=lua52
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test 
          packages:
          - gcc-4.8
          - g++-4.8  
          - ninja-build
          - liblua5.3-dev
    
    - os: linux
      env: COMPILER=clang++-3.4 LUA=lua53
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test 
          packages:
          - clang++-3.4
          - ninja-build
          - liblua5.3-dev

before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq 

script:
- echo "Configuration info:"
- export_compiler_vars
- ninja --version
- ./bootstrap.py --ci && ninja
